### ISSUE TITLE
Some confusion of the  thesis

### ISSUE THREAD

**Issue by LDoubleZhi** [Zzh-tju/DIoU#3]
The Giou visualization of the figure4, Why the errors of (10, 12) is smaller than (10, 13). The  C − A ∪ B in (10,13) is bigger than (10, 12)
`But the cases at horizontal and vertical
orientations are likely to still have large errors. This is be￾cause that the penalty term in GIoU loss is used to minimize
|C − A ∪ B|, but the area of C − A ∪ B is often small or
0 (when two boxes have inclusion relationships), and then
GIoU almost degrades to IoU loss`

**Comment by Zzh-tju** [comment]
what fig4 shows is the final error(sum for every regression cases on each point) of the anchor box to GT box at the 200 iteration. So since (10,13) is farther away than (10,12) in the beginning, it probably connot converge well. Think about that if a box is located in (10,100), 200 iterations is not enough for it to move to the GT box. Thus it may still in (10,20) and the error between the anchor and GT box will be large.

**Comment by LDoubleZhi** [comment]
@Zzh-tju Thanks!
